/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as MainRouteImport } from './routes/main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up.index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as MainIndexRouteImport } from './routes/main.index'
import { Route as SignUpVerifyEmailAddressRouteImport } from './routes/sign-up.verify-email-address'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as MainStatisticheRouteImport } from './routes/main.statistiche'
import { Route as MainSimulazioneQuizRouteImport } from './routes/main.simulazione-quiz'
import { Route as MainEsercitazioneRouteImport } from './routes/main.esercitazione'
import { Route as MainErroriRicorrentiRouteImport } from './routes/main.errori-ricorrenti'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const SignUpVerifyEmailAddressRoute =
  SignUpVerifyEmailAddressRouteImport.update({
    id: '/verify-email-address',
    path: '/verify-email-address',
    getParentRoute: () => SignUpRoute,
  } as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStatisticheRoute = MainStatisticheRouteImport.update({
  id: '/statistiche',
  path: '/statistiche',
  getParentRoute: () => MainRoute,
} as any)
const MainSimulazioneQuizRoute = MainSimulazioneQuizRouteImport.update({
  id: '/simulazione-quiz',
  path: '/simulazione-quiz',
  getParentRoute: () => MainRoute,
} as any)
const MainEsercitazioneRoute = MainEsercitazioneRouteImport.update({
  id: '/esercitazione',
  path: '/esercitazione',
  getParentRoute: () => MainRoute,
} as any)
const MainErroriRicorrentiRoute = MainErroriRicorrentiRouteImport.update({
  id: '/errori-ricorrenti',
  path: '/errori-ricorrenti',
  getParentRoute: () => MainRoute,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/main/errori-ricorrenti': typeof MainErroriRicorrentiRoute
  '/main/esercitazione': typeof MainEsercitazioneRoute
  '/main/simulazione-quiz': typeof MainSimulazioneQuizRoute
  '/main/statistiche': typeof MainStatisticheRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/verify-email-address': typeof SignUpVerifyEmailAddressRoute
  '/main/': typeof MainIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main/errori-ricorrenti': typeof MainErroriRicorrentiRoute
  '/main/esercitazione': typeof MainEsercitazioneRoute
  '/main/simulazione-quiz': typeof MainSimulazioneQuizRoute
  '/main/statistiche': typeof MainStatisticheRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/verify-email-address': typeof SignUpVerifyEmailAddressRoute
  '/main': typeof MainIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/main/errori-ricorrenti': typeof MainErroriRicorrentiRoute
  '/main/esercitazione': typeof MainEsercitazioneRoute
  '/main/simulazione-quiz': typeof MainSimulazioneQuizRoute
  '/main/statistiche': typeof MainStatisticheRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/verify-email-address': typeof SignUpVerifyEmailAddressRoute
  '/main/': typeof MainIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/sign-up'
    | '/main/errori-ricorrenti'
    | '/main/esercitazione'
    | '/main/simulazione-quiz'
    | '/main/statistiche'
    | '/sign-in/$'
    | '/sign-up/verify-email-address'
    | '/main/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/webhooks/clerk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main/errori-ricorrenti'
    | '/main/esercitazione'
    | '/main/simulazione-quiz'
    | '/main/statistiche'
    | '/sign-in/$'
    | '/sign-up/verify-email-address'
    | '/main'
    | '/sign-in'
    | '/sign-up'
    | '/api/webhooks/clerk'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/sign-up'
    | '/main/errori-ricorrenti'
    | '/main/esercitazione'
    | '/main/simulazione-quiz'
    | '/main/statistiche'
    | '/sign-in/$'
    | '/sign-up/verify-email-address'
    | '/main/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/webhooks/clerk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/sign-up/verify-email-address': {
      id: '/sign-up/verify-email-address'
      path: '/verify-email-address'
      fullPath: '/sign-up/verify-email-address'
      preLoaderRoute: typeof SignUpVerifyEmailAddressRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/statistiche': {
      id: '/main/statistiche'
      path: '/statistiche'
      fullPath: '/main/statistiche'
      preLoaderRoute: typeof MainStatisticheRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/simulazione-quiz': {
      id: '/main/simulazione-quiz'
      path: '/simulazione-quiz'
      fullPath: '/main/simulazione-quiz'
      preLoaderRoute: typeof MainSimulazioneQuizRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/esercitazione': {
      id: '/main/esercitazione'
      path: '/esercitazione'
      fullPath: '/main/esercitazione'
      preLoaderRoute: typeof MainEsercitazioneRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/errori-ricorrenti': {
      id: '/main/errori-ricorrenti'
      path: '/errori-ricorrenti'
      fullPath: '/main/errori-ricorrenti'
      preLoaderRoute: typeof MainErroriRicorrentiRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteChildren {
  MainErroriRicorrentiRoute: typeof MainErroriRicorrentiRoute
  MainEsercitazioneRoute: typeof MainEsercitazioneRoute
  MainSimulazioneQuizRoute: typeof MainSimulazioneQuizRoute
  MainStatisticheRoute: typeof MainStatisticheRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainErroriRicorrentiRoute: MainErroriRicorrentiRoute,
  MainEsercitazioneRoute: MainEsercitazioneRoute,
  MainSimulazioneQuizRoute: MainSimulazioneQuizRoute,
  MainStatisticheRoute: MainStatisticheRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface SignUpRouteChildren {
  SignUpVerifyEmailAddressRoute: typeof SignUpVerifyEmailAddressRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpVerifyEmailAddressRoute: SignUpVerifyEmailAddressRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
