/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as MainRouteImport } from './routes/main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up.index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as MainIndexRouteImport } from './routes/main.index'
import { Route as SignUpVerifyEmailAddressRouteImport } from './routes/sign-up.verify-email-address'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as MainStatisticheRouteImport } from './routes/main.statistiche'
import { Route as MainSimulazioneQuizRouteImport } from './routes/main.simulazione-quiz'
import { Route as MainRivediQuizRouteImport } from './routes/main.rivedi-quiz'
import { Route as MainEsercitazioneRouteImport } from './routes/main.esercitazione'
import { Route as MainErroriRicorrentiRouteImport } from './routes/main.errori-ricorrenti'
import { Route as MainErroriRicorrentiIndexRouteImport } from './routes/main.errori-ricorrenti/index'
import { Route as MainErroriRicorrentiTutteCategorieRouteImport } from './routes/main.errori-ricorrenti/tutte-categorie'
import { Route as MainErroriRicorrentiSkullSelezionateRouteImport } from './routes/main.errori-ricorrenti/skull-selezionate'
import { Route as MainErroriRicorrentiMaggioriErroriRouteImport } from './routes/main.errori-ricorrenti/maggiori-errori'
import { Route as MainErroriRicorrentiFocusSkullRouteImport } from './routes/main.errori-ricorrenti/focus-skull'
import { Route as MainErroriRicorrentiDomandeSbagliateRouteImport } from './routes/main.errori-ricorrenti/domande-sbagliate'
import { Route as MainErroriRicorrentiDomandeEsatteRouteImport } from './routes/main.errori-ricorrenti/domande-esatte'
import { Route as MainErroriRicorrentiCategorieCriticheRouteImport } from './routes/main.errori-ricorrenti/categorie-critiche'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignUpRoute,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const SignUpVerifyEmailAddressRoute =
  SignUpVerifyEmailAddressRouteImport.update({
    id: '/verify-email-address',
    path: '/verify-email-address',
    getParentRoute: () => SignUpRoute,
  } as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStatisticheRoute = MainStatisticheRouteImport.update({
  id: '/statistiche',
  path: '/statistiche',
  getParentRoute: () => MainRoute,
} as any)
const MainSimulazioneQuizRoute = MainSimulazioneQuizRouteImport.update({
  id: '/simulazione-quiz',
  path: '/simulazione-quiz',
  getParentRoute: () => MainRoute,
} as any)
const MainRivediQuizRoute = MainRivediQuizRouteImport.update({
  id: '/rivedi-quiz',
  path: '/rivedi-quiz',
  getParentRoute: () => MainRoute,
} as any)
const MainEsercitazioneRoute = MainEsercitazioneRouteImport.update({
  id: '/esercitazione',
  path: '/esercitazione',
  getParentRoute: () => MainRoute,
} as any)
const MainErroriRicorrentiRoute = MainErroriRicorrentiRouteImport.update({
  id: '/errori-ricorrenti',
  path: '/errori-ricorrenti',
  getParentRoute: () => MainRoute,
} as any)
const MainErroriRicorrentiIndexRoute =
  MainErroriRicorrentiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiTutteCategorieRoute =
  MainErroriRicorrentiTutteCategorieRouteImport.update({
    id: '/tutte-categorie',
    path: '/tutte-categorie',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiSkullSelezionateRoute =
  MainErroriRicorrentiSkullSelezionateRouteImport.update({
    id: '/skull-selezionate',
    path: '/skull-selezionate',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiMaggioriErroriRoute =
  MainErroriRicorrentiMaggioriErroriRouteImport.update({
    id: '/maggiori-errori',
    path: '/maggiori-errori',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiFocusSkullRoute =
  MainErroriRicorrentiFocusSkullRouteImport.update({
    id: '/focus-skull',
    path: '/focus-skull',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiDomandeSbagliateRoute =
  MainErroriRicorrentiDomandeSbagliateRouteImport.update({
    id: '/domande-sbagliate',
    path: '/domande-sbagliate',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiDomandeEsatteRoute =
  MainErroriRicorrentiDomandeEsatteRouteImport.update({
    id: '/domande-esatte',
    path: '/domande-esatte',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const MainErroriRicorrentiCategorieCriticheRoute =
  MainErroriRicorrentiCategorieCriticheRouteImport.update({
    id: '/categorie-critiche',
    path: '/categorie-critiche',
    getParentRoute: () => MainErroriRicorrentiRoute,
  } as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/main': typeof MainRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/main/errori-ricorrenti': typeof MainErroriRicorrentiRouteWithChildren
  '/main/esercitazione': typeof MainEsercitazioneRoute
  '/main/rivedi-quiz': typeof MainRivediQuizRoute
  '/main/simulazione-quiz': typeof MainSimulazioneQuizRoute
  '/main/statistiche': typeof MainStatisticheRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/verify-email-address': typeof SignUpVerifyEmailAddressRoute
  '/main/': typeof MainIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/main/errori-ricorrenti/categorie-critiche': typeof MainErroriRicorrentiCategorieCriticheRoute
  '/main/errori-ricorrenti/domande-esatte': typeof MainErroriRicorrentiDomandeEsatteRoute
  '/main/errori-ricorrenti/domande-sbagliate': typeof MainErroriRicorrentiDomandeSbagliateRoute
  '/main/errori-ricorrenti/focus-skull': typeof MainErroriRicorrentiFocusSkullRoute
  '/main/errori-ricorrenti/maggiori-errori': typeof MainErroriRicorrentiMaggioriErroriRoute
  '/main/errori-ricorrenti/skull-selezionate': typeof MainErroriRicorrentiSkullSelezionateRoute
  '/main/errori-ricorrenti/tutte-categorie': typeof MainErroriRicorrentiTutteCategorieRoute
  '/main/errori-ricorrenti/': typeof MainErroriRicorrentiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/main/esercitazione': typeof MainEsercitazioneRoute
  '/main/rivedi-quiz': typeof MainRivediQuizRoute
  '/main/simulazione-quiz': typeof MainSimulazioneQuizRoute
  '/main/statistiche': typeof MainStatisticheRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/verify-email-address': typeof SignUpVerifyEmailAddressRoute
  '/main': typeof MainIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/main/errori-ricorrenti/categorie-critiche': typeof MainErroriRicorrentiCategorieCriticheRoute
  '/main/errori-ricorrenti/domande-esatte': typeof MainErroriRicorrentiDomandeEsatteRoute
  '/main/errori-ricorrenti/domande-sbagliate': typeof MainErroriRicorrentiDomandeSbagliateRoute
  '/main/errori-ricorrenti/focus-skull': typeof MainErroriRicorrentiFocusSkullRoute
  '/main/errori-ricorrenti/maggiori-errori': typeof MainErroriRicorrentiMaggioriErroriRoute
  '/main/errori-ricorrenti/skull-selezionate': typeof MainErroriRicorrentiSkullSelezionateRoute
  '/main/errori-ricorrenti/tutte-categorie': typeof MainErroriRicorrentiTutteCategorieRoute
  '/main/errori-ricorrenti': typeof MainErroriRicorrentiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/main': typeof MainRouteWithChildren
  '/sign-up': typeof SignUpRouteWithChildren
  '/main/errori-ricorrenti': typeof MainErroriRicorrentiRouteWithChildren
  '/main/esercitazione': typeof MainEsercitazioneRoute
  '/main/rivedi-quiz': typeof MainRivediQuizRoute
  '/main/simulazione-quiz': typeof MainSimulazioneQuizRoute
  '/main/statistiche': typeof MainStatisticheRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/verify-email-address': typeof SignUpVerifyEmailAddressRoute
  '/main/': typeof MainIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/main/errori-ricorrenti/categorie-critiche': typeof MainErroriRicorrentiCategorieCriticheRoute
  '/main/errori-ricorrenti/domande-esatte': typeof MainErroriRicorrentiDomandeEsatteRoute
  '/main/errori-ricorrenti/domande-sbagliate': typeof MainErroriRicorrentiDomandeSbagliateRoute
  '/main/errori-ricorrenti/focus-skull': typeof MainErroriRicorrentiFocusSkullRoute
  '/main/errori-ricorrenti/maggiori-errori': typeof MainErroriRicorrentiMaggioriErroriRoute
  '/main/errori-ricorrenti/skull-selezionate': typeof MainErroriRicorrentiSkullSelezionateRoute
  '/main/errori-ricorrenti/tutte-categorie': typeof MainErroriRicorrentiTutteCategorieRoute
  '/main/errori-ricorrenti/': typeof MainErroriRicorrentiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/main'
    | '/sign-up'
    | '/main/errori-ricorrenti'
    | '/main/esercitazione'
    | '/main/rivedi-quiz'
    | '/main/simulazione-quiz'
    | '/main/statistiche'
    | '/sign-in/$'
    | '/sign-up/verify-email-address'
    | '/main/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/webhooks/clerk'
    | '/main/errori-ricorrenti/categorie-critiche'
    | '/main/errori-ricorrenti/domande-esatte'
    | '/main/errori-ricorrenti/domande-sbagliate'
    | '/main/errori-ricorrenti/focus-skull'
    | '/main/errori-ricorrenti/maggiori-errori'
    | '/main/errori-ricorrenti/skull-selezionate'
    | '/main/errori-ricorrenti/tutte-categorie'
    | '/main/errori-ricorrenti/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/main/esercitazione'
    | '/main/rivedi-quiz'
    | '/main/simulazione-quiz'
    | '/main/statistiche'
    | '/sign-in/$'
    | '/sign-up/verify-email-address'
    | '/main'
    | '/sign-in'
    | '/sign-up'
    | '/api/webhooks/clerk'
    | '/main/errori-ricorrenti/categorie-critiche'
    | '/main/errori-ricorrenti/domande-esatte'
    | '/main/errori-ricorrenti/domande-sbagliate'
    | '/main/errori-ricorrenti/focus-skull'
    | '/main/errori-ricorrenti/maggiori-errori'
    | '/main/errori-ricorrenti/skull-selezionate'
    | '/main/errori-ricorrenti/tutte-categorie'
    | '/main/errori-ricorrenti'
  id:
    | '__root__'
    | '/'
    | '/main'
    | '/sign-up'
    | '/main/errori-ricorrenti'
    | '/main/esercitazione'
    | '/main/rivedi-quiz'
    | '/main/simulazione-quiz'
    | '/main/statistiche'
    | '/sign-in/$'
    | '/sign-up/verify-email-address'
    | '/main/'
    | '/sign-in/'
    | '/sign-up/'
    | '/api/webhooks/clerk'
    | '/main/errori-ricorrenti/categorie-critiche'
    | '/main/errori-ricorrenti/domande-esatte'
    | '/main/errori-ricorrenti/domande-sbagliate'
    | '/main/errori-ricorrenti/focus-skull'
    | '/main/errori-ricorrenti/maggiori-errori'
    | '/main/errori-ricorrenti/skull-selezionate'
    | '/main/errori-ricorrenti/tutte-categorie'
    | '/main/errori-ricorrenti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  SignUpRoute: typeof SignUpRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/sign-up/verify-email-address': {
      id: '/sign-up/verify-email-address'
      path: '/verify-email-address'
      fullPath: '/sign-up/verify-email-address'
      preLoaderRoute: typeof SignUpVerifyEmailAddressRouteImport
      parentRoute: typeof SignUpRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/statistiche': {
      id: '/main/statistiche'
      path: '/statistiche'
      fullPath: '/main/statistiche'
      preLoaderRoute: typeof MainStatisticheRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/simulazione-quiz': {
      id: '/main/simulazione-quiz'
      path: '/simulazione-quiz'
      fullPath: '/main/simulazione-quiz'
      preLoaderRoute: typeof MainSimulazioneQuizRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/rivedi-quiz': {
      id: '/main/rivedi-quiz'
      path: '/rivedi-quiz'
      fullPath: '/main/rivedi-quiz'
      preLoaderRoute: typeof MainRivediQuizRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/esercitazione': {
      id: '/main/esercitazione'
      path: '/esercitazione'
      fullPath: '/main/esercitazione'
      preLoaderRoute: typeof MainEsercitazioneRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/errori-ricorrenti': {
      id: '/main/errori-ricorrenti'
      path: '/errori-ricorrenti'
      fullPath: '/main/errori-ricorrenti'
      preLoaderRoute: typeof MainErroriRicorrentiRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/errori-ricorrenti/': {
      id: '/main/errori-ricorrenti/'
      path: '/'
      fullPath: '/main/errori-ricorrenti/'
      preLoaderRoute: typeof MainErroriRicorrentiIndexRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/tutte-categorie': {
      id: '/main/errori-ricorrenti/tutte-categorie'
      path: '/tutte-categorie'
      fullPath: '/main/errori-ricorrenti/tutte-categorie'
      preLoaderRoute: typeof MainErroriRicorrentiTutteCategorieRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/skull-selezionate': {
      id: '/main/errori-ricorrenti/skull-selezionate'
      path: '/skull-selezionate'
      fullPath: '/main/errori-ricorrenti/skull-selezionate'
      preLoaderRoute: typeof MainErroriRicorrentiSkullSelezionateRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/maggiori-errori': {
      id: '/main/errori-ricorrenti/maggiori-errori'
      path: '/maggiori-errori'
      fullPath: '/main/errori-ricorrenti/maggiori-errori'
      preLoaderRoute: typeof MainErroriRicorrentiMaggioriErroriRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/focus-skull': {
      id: '/main/errori-ricorrenti/focus-skull'
      path: '/focus-skull'
      fullPath: '/main/errori-ricorrenti/focus-skull'
      preLoaderRoute: typeof MainErroriRicorrentiFocusSkullRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/domande-sbagliate': {
      id: '/main/errori-ricorrenti/domande-sbagliate'
      path: '/domande-sbagliate'
      fullPath: '/main/errori-ricorrenti/domande-sbagliate'
      preLoaderRoute: typeof MainErroriRicorrentiDomandeSbagliateRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/domande-esatte': {
      id: '/main/errori-ricorrenti/domande-esatte'
      path: '/domande-esatte'
      fullPath: '/main/errori-ricorrenti/domande-esatte'
      preLoaderRoute: typeof MainErroriRicorrentiDomandeEsatteRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/main/errori-ricorrenti/categorie-critiche': {
      id: '/main/errori-ricorrenti/categorie-critiche'
      path: '/categorie-critiche'
      fullPath: '/main/errori-ricorrenti/categorie-critiche'
      preLoaderRoute: typeof MainErroriRicorrentiCategorieCriticheRouteImport
      parentRoute: typeof MainErroriRicorrentiRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainErroriRicorrentiRouteChildren {
  MainErroriRicorrentiCategorieCriticheRoute: typeof MainErroriRicorrentiCategorieCriticheRoute
  MainErroriRicorrentiDomandeEsatteRoute: typeof MainErroriRicorrentiDomandeEsatteRoute
  MainErroriRicorrentiDomandeSbagliateRoute: typeof MainErroriRicorrentiDomandeSbagliateRoute
  MainErroriRicorrentiFocusSkullRoute: typeof MainErroriRicorrentiFocusSkullRoute
  MainErroriRicorrentiMaggioriErroriRoute: typeof MainErroriRicorrentiMaggioriErroriRoute
  MainErroriRicorrentiSkullSelezionateRoute: typeof MainErroriRicorrentiSkullSelezionateRoute
  MainErroriRicorrentiTutteCategorieRoute: typeof MainErroriRicorrentiTutteCategorieRoute
  MainErroriRicorrentiIndexRoute: typeof MainErroriRicorrentiIndexRoute
}

const MainErroriRicorrentiRouteChildren: MainErroriRicorrentiRouteChildren = {
  MainErroriRicorrentiCategorieCriticheRoute:
    MainErroriRicorrentiCategorieCriticheRoute,
  MainErroriRicorrentiDomandeEsatteRoute:
    MainErroriRicorrentiDomandeEsatteRoute,
  MainErroriRicorrentiDomandeSbagliateRoute:
    MainErroriRicorrentiDomandeSbagliateRoute,
  MainErroriRicorrentiFocusSkullRoute: MainErroriRicorrentiFocusSkullRoute,
  MainErroriRicorrentiMaggioriErroriRoute:
    MainErroriRicorrentiMaggioriErroriRoute,
  MainErroriRicorrentiSkullSelezionateRoute:
    MainErroriRicorrentiSkullSelezionateRoute,
  MainErroriRicorrentiTutteCategorieRoute:
    MainErroriRicorrentiTutteCategorieRoute,
  MainErroriRicorrentiIndexRoute: MainErroriRicorrentiIndexRoute,
}

const MainErroriRicorrentiRouteWithChildren =
  MainErroriRicorrentiRoute._addFileChildren(MainErroriRicorrentiRouteChildren)

interface MainRouteChildren {
  MainErroriRicorrentiRoute: typeof MainErroriRicorrentiRouteWithChildren
  MainEsercitazioneRoute: typeof MainEsercitazioneRoute
  MainRivediQuizRoute: typeof MainRivediQuizRoute
  MainSimulazioneQuizRoute: typeof MainSimulazioneQuizRoute
  MainStatisticheRoute: typeof MainStatisticheRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainErroriRicorrentiRoute: MainErroriRicorrentiRouteWithChildren,
  MainEsercitazioneRoute: MainEsercitazioneRoute,
  MainRivediQuizRoute: MainRivediQuizRoute,
  MainSimulazioneQuizRoute: MainSimulazioneQuizRoute,
  MainStatisticheRoute: MainStatisticheRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface SignUpRouteChildren {
  SignUpVerifyEmailAddressRoute: typeof SignUpVerifyEmailAddressRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

const SignUpRouteChildren: SignUpRouteChildren = {
  SignUpVerifyEmailAddressRoute: SignUpVerifyEmailAddressRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}

const SignUpRouteWithChildren =
  SignUpRoute._addFileChildren(SignUpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  SignUpRoute: SignUpRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
